### ISSUE TITLE
rpmlint reports E: incorrect-fsf-address /usr/share/licenses/noad/COPYING

### ISSUE THREAD

**Issue by martinkg** [madmartin/noad#1]
rpmlint reports the error:

noad.x86_64: E: incorrect-fsf-address /usr/share/licenses/noad/COPYING
The Free Software Foundation address in this file seems to be outdated or
misspelled.  Ask upstream to update the address, or if this is a license file,
possibly the entire file with a new copy available from the FSF.

fixed with the following patch:
[noad-0.8.7-fsf-fix.patch.txt](https://github.com/madmartin/noad/files/6701212/noad-0.8.7-fsf-fix.patch.txt)

**Comment by madmartin** [comment]
Hi,
you may be right. I'll fix this. Thanks for reporting!
